name: lint
on: [push, pull_request]

jobs:
  lint:
    strategy:
      matrix:
        src-dir: ["./elleelleaime", "./tests"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Run linter
        uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e # v26.5.1
        with:
          options: "--check --verbose"
          src: ${{ matrix.src-dir }}
          version: "24.4.2"
